dataset:
  train:
    name: hypersim
    disp_name: hypersim_train
    # dir: hypersim/hypersim_processed_train.tar
    dir: Hypersim/processed/train
    filenames: data_split/hypersim/filename_list_train_filtered_subset.txt
    resize_to_hw:
    - 480
    - 640
