dataset:
  hypersim:
    name: 'hypersim'
    disp_name: 'hypersim_train'
    dir: 'Hypersim/processed/train'
    filenames: 'data_split/hypersim/filename_list_train_filtered.txt'
    resize_to_hw: [512, 512]

    val_filenames: '/mnt/51eb0667-f71d-4fe0-a83e-beaff24c04fb/om/depth_estimation_experiments/DiT/data_split/hypersim/selected_vis_sample.txt'
    val_dir: 'Hypersim/processed/val'
      
depth_transform:
  type: 'scale_shift_depth'
  clip: true
  norm_min: -1.0
  norm_max: 1.0
  min_max_quantile: 0.02

augmentation_args:
  lr_flip_p: 0.5

multi_res_noise:
  annealed: true
  strength: 0.9
  downscale_strategy: 'original'

paths:
  base_data_dir: '/mnt/51eb0667-f71d-4fe0-a83e-beaff24c04fb/om/depth_estimation_experiments/Marigold/data'
  val_data_dir: '/mnt/51eb0667-f71d-4fe0-a83e-beaff24c04fb/om/depth_estimation_experiments/DiT/data_split/hypersim'
