dataset:
  train:
    name: mixed
    prob_ls: [0.9, 0.1]
    dataset_list:
    - name: hypersim
      disp_name: hypersim_train
      dir: Hypersim/Hypersim-Processed/train
      filenames: data_split/hypersim/filename_list_train_filtered_subset.txt 
    - name: vkitti
      disp_name: vkitti_train
      dir: vkitti2
      filenames: data_split/vkitti/vkitti_train_subset.txt
      kitti_bm_crop: true
      valid_mask_crop: null


  val:
    name: mixed
    dataset_list:
      - name: hypersim
        disp_name: hypersim_vis_small
        dir: Hypersim/Hypersim-Processed/train
        filenames: data_split/hypersim/selected_vis_sample_subset.txt
      - name: vkitti
        disp_name: vkitti_vis
        dir: vkitti2
        filenames: data_split/vkitti/vkitti_overfitting_vis.txt
        kitti_bm_crop: true
        valid_mask_crop: null


depth_normalization:
  type: scale_shift_depth
  clip: true
  norm_min: -1.0
  norm_max: 1.0
  min_max_quantile: 0.02

augmentation:
  lr_flip_p: 0.5

validation:
  cfg_scale: 4.0
  diffusion_steps: 20
  scheduler: 'ddim'
  batch_size: 1

paths:
  base_data_dir: '/mnt/51eb0667-f71d-4fe0-a83e-beaff24c04fb/om/depth_estimation_experiments/depth_datasets'
